### ISSUE TITLE
Add SwiftLint

### ISSUE THREAD

**Issue by guseducampos** [CacaoSV/Study-Path-Traker-App#3]
For keep the code clean and readable I believe is necessary add swift lint.  cc @Rflpz @ifobos

**Comment by ifobos** [comment]
right, we are going to use the most recent version of the swiftLint configuration file that should be in confluence, otherwise ask @nelson-rivera

**Comment by Rflpz** [comment]
I'm on it

**Comment by guseducampos** [comment]
Swift Lint was added. I'll close the issue.
